In [1]:
#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#NUMPY


# In[4]:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

arr.data

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [4]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [5]:
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
arr.shape


(5,)

In [7]:
arr.size


5

In [8]:
arr.ndim

1

In [9]:
arr.nbytes



40

In [10]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
len(arr)

5

In [13]:
np.repeat(4,3)

array([4, 4, 4])

In [15]:
x = np.arange(1, 10)

n= x[ (x % 5 == 0)]


In [16]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [17]:
x = np.arange(1, 100)

n= x[ (x % 5 == 0)]
print(n)


[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [18]:
np.linspace(10,20,3)

array([10., 15., 20.])

In [19]:
np.random.random(4)

array([0.12674903, 0.46824479, 0.94298778, 0.36629872])

In [20]:
a=np.random.uniform(4,10,8)
print(a)

[9.5648824  5.64195251 6.52620709 5.92254744 6.06582728 5.56506668
 4.35051976 6.66796698]


In [21]:
np.floor(a)

array([9., 5., 6., 5., 6., 5., 4., 6.])

In [ ]:
np.trunc(a)


In [22]:
np.sum(a)

50.30497013737945

In [23]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 6, 4, 5])
print(arr1) 
print(arr2) 

[1 2 3 4 5]
[1 2 6 4 5]


In [25]:
np.sum(arr1+arr2)


# In[57]:


np.sum(arr1-arr2)


# In[58]:


np.product(arr1*arr2)


# In[67]:


np.sum(arr1 / arr2)

4.5

In [26]:
s = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.median(s)

print(x)


# In[70]:


s = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = np.mode(s)

print(x)

87.0


AttributeError: module 'numpy' has no attribute 'mode'

In [27]:
#dimension
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[22,33,44]]])
print (a1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [22 33 44]]]


In [28]:
import numpy as np
a1=np.array([11,24,34,46])
np.add(a1[0],a1[2])


45

In [29]:
np.subtract(a1[1],a1[2])

-10

In [30]:
np.multiply(a1[1],a1[2])

816

In [31]:
import numpy as np
a6=np.array([[1,2,3],[22,33,44]])
print (a6)

[[ 1  2  3]
 [22 33 44]]


In [32]:
print (a6[0,2])

3


In [33]:
print (a6[1,2])

44


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [35]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
#operation on array 

a=np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
a.sum()

155

In [19]:
#cummulation
np.cumsum(a)

array([ 11,  23,  36,  50,  65,  81,  98, 116, 135, 155])

In [20]:
#min number in an array
a.min()

11

In [21]:
a.max()

20

In [22]:
a.mean()

15.5

In [24]:
np.median(a)

15.5

In [27]:
a.argmin()

0

In [28]:
#index min
a.argmax()

9

In [30]:
#variance
np.var(a)

8.25

In [31]:
#standard davination
np.std(a)

2.8722813232690143

In [32]:
#percentilies
np.percentile(a,65)

16.85

In [37]:
#copy and veiw
import numpy as np

arr = np.array([11, 25, 35, 43, 55])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42 25 35 43 55]
[11 25 35 43 55]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()



print(x)


[1 2 3 4 5]


In [39]:
import numpy as np

arr = np.array([11, 25, 35, 43, 55])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[11 25 35 43 55]


In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [3]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [9]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)
arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
